# Generated by Django 5.0.4 on 2024-05-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="department",
            field=models.CharField(default="Computer Science", max_length=100),
        ),
    ]
