# Generated by Django 5.0.4 on 2024-05-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_faculty_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
    ]
