# Generated by Django 5.0.4 on 2024-05-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_faculty_about_student_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="faculty",
            name="contact_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="faculty",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="faculty",
            name="expertise",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
