# Generated by Django 5.0.4 on 2024-05-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_batch_student_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="course",
            field=models.CharField(default="bca", max_length=100),
        ),
    ]
