# Generated by Django 5.0.6 on 2024-05-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='expertise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
