# Generated by Django 5.0.6 on 2024-05-21 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_committee_membership_education_experience_honors_and_more"),
        ("users", "0005_faculty_address_faculty_contact_number_faculty_dob_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.faculty",
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="experience",
            name="is_pending",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="honors",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approving_faculty",
                to="users.faculty",
            ),
        ),
        migrations.AddField(
            model_name="honors",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="honors",
            name="is_pending",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="patent",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.faculty",
            ),
        ),
        migrations.AddField(
            model_name="patent",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patent",
            name="is_pending",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.faculty",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="publication",
            name="is_pending",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.faculty",
            ),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="is_pending",
            field=models.BooleanField(default=True),
        ),
    ]
