# Generated by Django 5.0.4 on 2024-05-23 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("home", "0008_remove_education_student_and_more"),
        ("users", "0008_student_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Committee_membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225)),
                ("organization", models.CharField(max_length=225)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("description", models.TextField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="committee_memberships",
                        to="users.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school", models.CharField(max_length=225)),
                ("degree", models.CharField(max_length=225)),
                ("field_of_study", models.CharField(max_length=225)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("grade", models.CharField(max_length=10)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="users.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=225)),
                (
                    "department",
                    models.CharField(default="Computer Applications", max_length=225),
                ),
                ("employment_type", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=225)),
                ("location", models.CharField(max_length=225)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("description", models.TextField()),
                ("is_approved", models.BooleanField(default=False)),
                ("is_pending", models.BooleanField(default=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.faculty",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="users.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Honors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic"),
                            ("non_academic", "Non-Academic"),
                        ],
                        max_length=255,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("is_approved", models.BooleanField(default=False)),
                ("is_pending", models.BooleanField(default=True)),
                ("issuing_organization", models.CharField(max_length=225)),
                (
                    "issue_year",
                    models.IntegerField(
                        choices=[
                            (1980, 1980),
                            (1981, 1981),
                            (1982, 1982),
                            (1983, 1983),
                            (1984, 1984),
                            (1985, 1985),
                            (1986, 1986),
                            (1987, 1987),
                            (1988, 1988),
                            (1989, 1989),
                            (1990, 1990),
                            (1991, 1991),
                            (1992, 1992),
                            (1993, 1993),
                            (1994, 1994),
                            (1995, 1995),
                            (1996, 1996),
                            (1997, 1997),
                            (1998, 1998),
                            (1999, 1999),
                            (2000, 2000),
                            (2001, 2001),
                            (2002, 2002),
                            (2003, 2003),
                            (2004, 2004),
                            (2005, 2005),
                            (2006, 2006),
                            (2007, 2007),
                            (2008, 2008),
                            (2009, 2009),
                            (2010, 2010),
                            (2011, 2011),
                            (2012, 2012),
                            (2013, 2013),
                            (2014, 2014),
                            (2015, 2015),
                            (2016, 2016),
                            (2017, 2017),
                            (2018, 2018),
                            (2019, 2019),
                            (2020, 2020),
                            (2021, 2021),
                            (2022, 2022),
                            (2023, 2023),
                            (2024, 2024),
                        ],
                        default=2024,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_approved",
                        to="users.faculty",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.student"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Patent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic"),
                            ("non_academic", "Non-Academic"),
                        ],
                        max_length=255,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("is_approved", models.BooleanField(default=False)),
                ("is_pending", models.BooleanField(default=True)),
                ("inventors", models.CharField(max_length=225)),
                ("application_number", models.CharField(max_length=225)),
                ("patent_number", models.CharField(max_length=225)),
                ("filing_country", models.CharField(max_length=225)),
                ("subject_category", models.CharField(max_length=225)),
                ("filing_date", models.DateField()),
                ("publication_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("published", "Published"),
                            ("granted", "Granted"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_approved",
                        to="users.faculty",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.student"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic"),
                            ("non_academic", "Non-Academic"),
                        ],
                        max_length=255,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("is_approved", models.BooleanField(default=False)),
                ("is_pending", models.BooleanField(default=True)),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("article_in_press", "Article in Press"),
                            ("book", "Book"),
                            ("book_chapter", "Book Chapter"),
                            ("conference_paper", "Conference Paper"),
                            ("conference_proceedings", "Conference Proceedings"),
                            ("editorial", "Editorial"),
                            ("erratum", "Erratum"),
                            ("letter", "Letter"),
                            ("note", "Note"),
                            ("review", "Review"),
                            ("retracted_article", "Retracted Article"),
                            ("short_survey", "Short Survey"),
                            ("other", "Other"),
                        ],
                        default="article",
                        max_length=225,
                    ),
                ),
                (
                    "journal_name",
                    models.CharField(default="ABC Journal", max_length=225),
                ),
                ("authors", models.CharField(max_length=225)),
                ("doi", models.CharField(blank=True, max_length=225, null=True)),
                (
                    "issuing_organization",
                    models.CharField(default="Unknown Organization", max_length=225),
                ),
                ("issue_date", models.DateField()),
                ("url", models.URLField(blank=True, null=True)),
                ("volume", models.CharField(blank=True, max_length=225, null=True)),
                (
                    "page_number",
                    models.CharField(blank=True, max_length=225, null=True),
                ),
                (
                    "publisher_name",
                    models.CharField(blank=True, max_length=225, null=True),
                ),
                ("file", models.FileField(upload_to="publications/")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_approved",
                        to="users.faculty",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.student"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResearchProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic"),
                            ("non_academic", "Non-Academic"),
                        ],
                        max_length=255,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("is_approved", models.BooleanField(default=False)),
                ("is_pending", models.BooleanField(default=True)),
                ("role", models.CharField(max_length=225)),
                ("funding_agency", models.CharField(max_length=225)),
                ("grant_number", models.CharField(max_length=225)),
                (
                    "status",
                    models.CharField(
                        choices=[("completed", "Completed"), ("ongoing", "Ongoing")],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ongoing", models.BooleanField(default=False)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_approved",
                        to="users.faculty",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.student"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
