# Generated by Django 5.0.4 on 2024-05-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_honors_date_alter_patent_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchproject",
            name="end_date",
            field=models.DateField(default="2024-05-03"),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="start_date",
            field=models.DateField(default="2024-02-05"),
        ),
    ]
